services:
  postgres:
    image: postgres:16-alpine
    container_name: ef_lab_postgres
    environment:
      POSTGRES_USER: efuser
      POSTGRES_PASSWORD: efpass
      POSTGRES_DB: ef_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U efuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
